### ISSUE TITLE
how much do I want.

### ISSUE THREAD

**Issue by lymanlai** [open-company/salary#1]
1. I want to try 10000 RMB at the first month.
2. If all things goes all right, and the project goes pretty good, I will rais the salary.
3. The final monthly salary for this job I think it will be 30000RMB + project bonus(if the project start earn money)

**Comment by open-company** [comment]
The specific amount is not a problem.
You should provide how you calculate your salary, and according to which data you can get from github API. (e.g. code sloc, commits numbers and rate)
You don't need provide a algorithm right now, but you have to express you salary process detail like a programer and boss.
After done this, you'll be a real boss of your project.

**Comment by lymanlai** [comment]
I calculate the salary base on the idea that if we need to hire a programmer like me, how much we should cost. 
as this position it require these ability:
1. English document reading
2. javascript base, css, 
3. nodejs, react etc.
4. have idea and want to make this idea good, this is the most important.

and the guy will work at least 8 hours / day and keep 100% working time work
(because this is a remote work and the guy is the worker and the boss both! he is work for himself!)
and also, if the project growth, and it works and also make money, then the boss and worker will get more income(the boss and worker is the same guy at this case)

For the salary caculation: 
1. I think we will caculate base on the task commit number 
2. but every commit task should be all the same weight.

**Comment by open-company** [comment]
OK, I see it.
